name = "ldc-shop"
main = "worker.js"
compatibility_date = "2023-01-01"

# Custom Domain (replace with your domain)
routes = [
{ pattern = "shop.novacog.me", custom_domain = true }
]

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "ldc-shop-db"
database_id = "e2a1f5fd-ec49-4ddd-a3fc-f5dd3fa2a987"
# preview_database_id = "DB" # Use strictly for local dev
